// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbkqvdgmotuwzxofpzmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impia3F2ZGdtb3R1d3p4b2Zwem1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NDgzNDQsImV4cCI6MjA3NDEyNDM0NH0.I9tGLt4OEY73F88XPEDEVO7gZRXlRsszgnsjLfioGmM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});